version: '3.8'

services:
  # Service pour Symfony (application PHP)
  php:
    build:
      context: .
      dockerfile: Dockerfile-php
    image: mass18/freelance_plateform
    container_name: freelance_php
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    environment:
      SYMFONY_ENV: dev
    networks:
      - symfony-network

  # Service pour le serveur web Nginx
  web:
    image: nginx:latest
    container_name: freelance_web
    depends_on:
      - php
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      # - "/c/xampp/htdocs/freelance_platform/docker/nginx/nginx.conf:/etc/nginx/nginx.conf"

    networks:
      - symfony-network

  # Service pour la base de données MySQL
  db:
    image: mysql:5.7
    container_name: freelance_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - symfony-network

  # Service pour phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: freelance_phpmyadmin_contain
    depends_on:
      - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "8080:80"
    networks:
      - symfony-network

volumes:
  db_data:

networks:
  symfony-network:
    driver: bridge
