# controllers:
#     resource:
        # path: ../src/Controller/
        # namespace: App\Controller
        # type: attribute

app_global_controllers:
      resource: ../src/Domain/
      type: attribute
      prefix: /

app_domain_controllers:
      resource: ../src/Domain/
      type: attribute
      prefix: /  
